---
title: "Machine Learning Project"
author: "Chase, Ayushi, Rodrigo"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#plotting and exploring
library(tidyverse) #for plotting and summarizing
library(GGally) #for nice scatterplot matrix 
library(ggridges) #for joy/ridge plots
library(corrplot) #for basic correlation matrix plot
library(naniar) #for exploring missing values
library(pdp) #for partial dependence plots, MARS models
library(rpart.plot) #for plotting decision trees
library(vip) #for importance plots
library(pROC) #for ROC curves
library(plotROC) #for plotting ROC curves

#making things look nice
library(lubridate) #for nice dates
library(knitr) #for nice tables
library(scales) #for nice labels on graphs
library(gridExtra) #for arranging plots
library(broom) #for nice model output
library(janitor) #for nice names

#data
library(ISLR) #for data
library(moderndive) #for data
library(rattle) #weather data

#modeling
library(rsample) #for splitting data
library(recipes) #for keeping track of transformations
library(caret) #for modeling
library(leaps) #for variable selection
library(glmnet) #for LASSO
library(earth) #for MARS models
library(rpart) #for decision trees
library(randomForest) #for bagging and random forests
```

```{r}
#read in the data
wine <- read_csv("winequality-red.csv")
```

Research question:
How to determine which physiochemical properties make wine 'good'?

Splitting the data into test and training data
```{r}
set.seed(327) 

#70% for training, 30% for test
wine_split <- initial_split(wine, 
                               prop = .7)
wine_train <- training(wine_split)
wine_test <- testing(wine_split)
```


Taking the data out for a walk:
```{r}
graph1 <- wine_train%>%
  ggplot(aes(x = quality))+
  geom_bar()

graph2 <- wine_train%>%
  ggplot(aes(x = `fixed acidity`, y=density))+
  geom_point()

graph3 <- wine_train%>%
  ggplot(aes(x=density, y=pH))+
  geom_point()

graph4 <- wine_train%>%
  ggplot(aes(x=`fixed acidity`, y=pH))+
  geom_point()

graph5 <- wine_train%>%
  ggplot(aes(x=`free sulfur dioxide`, y=`total sulfur dioxide`))+
  geom_point()

graph6 <- wine_train%>%
  ggplot(aes(x=sulphates, y=alcohol))+
  geom_point()

graph7 <- wine_train%>%
  ggplot(aes(x=`residual sugar`, y=density))+
  geom_point()

graph8 <- wine_train%>%
  ggplot(aes(x=chlorides, y=density))+
  geom_point()

graph9 <- wine_train%>%
  ggplot(aes(x=alcohol, y=chlorides))+
  geom_point()

grid.arrange(graph1, graph2, graph3, nrow=1)
grid.arrange(graph4, graph5, graph6, nrow=2)
grid.arrange(graph7, graph8, graph9, nrow=3)



```

